on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    strategy:
      fail-fast: false
      matrix:
        job_name: ["build"]
        job_phrase: ["Build env"]
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request_target' ||
      (github.event_name == 'schedule' && github.repository == 'apache/beam') ||
      github.event_name == 'workflow_dispatch' ||
      github.event.comment.body == 'Run Job Phrase'
    env:
      DOCKER_INTERACTIVE_RUN: ""
    steps:
      - uses: actions/checkout@v4
      - name: Setup repository
        uses: ./.github/actions/setup-action
        with:
          comment_phrase: ${{ matrix.job_phrase }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
      - name: Setup env
        run: ./start-build-env.sh ./gradlew checkSetup